apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-reviews-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-reviews
  template:
    metadata:
      labels:
        app: mongodb-reviews
    spec:
      containers:
      - name: mongodb-reviews
        image: mongo:5.0.5
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-catalog-store-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-catalog-store
  template:
    metadata:
      labels:
        app: mysql-catalog-store
    spec:
      containers:
      - name: mysql-catalog-store
        image: mysql:8.0.27
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: catalog-library

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9.13-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-reviews-service
spec:
  type: NodePort
  selector:
    app: mongodb-reviews
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32460
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-catalog-store-service
spec:
  type: NodePort
  selector:
    app: mysql-catalog-store
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      name: puerto1
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: puerto2
      port: 15672
      targetPort: 15672

